### ISSUE TITLE
[Frontend - Exclusão de Postagens] Como um usuário, quero deletar um post.

### ISSUE THREAD

**Issue by RabbitDeWitt** [Hanami-Staff/Squad14-FrontEnd#3]
***Descrição:***
Deve haver uma opção para deletar um post na interface do usuário. Essa ação deve pedir uma confirmação para evitar exclusões acidentais e um usuário só pode excluir o próprio post.

***Critérios de Aceitação:***

- Cada post listado deve ter um botão de 'deletar'.
- Uma confirmação deve ser solicitada antes de realizar a exclusão.
- Após a exclusão, o post deve desaparecer da lista imediatamente.

***Tasks:***

- [x]  Adicionar botões de deletar em cada post.
- [x]  Implementar uma confirmação de exclusão.
- [x]  Integrar a funcionalidade de deleção com a API.
