### ISSUE TITLE
[Frontend - Criação de Postagens] Como um usuário, quero criar um novo post.

### ISSUE THREAD

**Issue by RabbitDeWitt** [Hanami-Staff/Squad14-FrontEnd#5]
***Descrição*:**
A interface deve fornecer um formulário simples para a criação de um novo post, incluindo campos para título e conteúdo.

***Critérios de Aceitação:***

- O formulário deve validar a entrada para garantir que nenhum campo obrigatório esteja vazio.
- Após a criação, o usuário deve receber uma confirmação.
- O novo post deve aparecer na lista de posts sem a necessidade de recarregar a página.

**Tasks:**

- [x]  Criar um formulário para inserção de novos posts.
- [x]  Implementar validação de campos no lado do cliente.
- [x]  Configurar a submissão de dados para a API.
- [x]  Atualizar a interface para mostrar o novo post imediatamente.
